AWSTemplateFormatVersion: "2010-09-09"

Description: An exercise template with SecretsManager and RDS Database

Parameters:
  AppDbName:
    Type: String
  DbUser:
    Type: String

Resources:
  TiinaSecretManager:
    Type: AWS::SecretsManager::Secret
    Properties:
        GenerateSecretString:
          PasswordLength: 30
          ExcludePunctuation: true
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG for EC2 and DB"
      GroupName: TiinaDBsecurityGroupCF
      Tags: 
        - Key: "DBsecGroup"
          Value: "DBSG"
      SecurityGroupIngress: 
        - FromPort: 3306
          ToPort: 3306
          IpProtocol: TCP
          CidrIp: 109.204.206.210/32
  MyDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 20
        DBInstanceClass: db.t2.micro
        DBName: !Ref AppDbName
        Engine: mysql
        MasterUsername: !Ref DbUser
        MasterUserPassword: !Sub '{{resolve:secretsmanager:${TiinaSecretManager}}}'
        BackupRetentionPeriod: 0
        VPCSecurityGroups:
          - !GetAtt DBSecurityGroup.GroupId